name: 雷神自动停止加速

on:
  push:
  schedule:
   # 定时任务，北京时间3点执行任务 3:00（北京时间）-8:00 = -18:00(24进制)cron指定的是格林尼治时间（UTC），如果需要换算成北京时间，要在该cron的基础上增加八小时得到北京时间
    - cron: '00 19 * * *' #第一个数字代表分钟，第二个数字代表小时，第三个数字代表日，第四个数字代表月，第五个数字代表星期。

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: "雷神加速器暂停脚本"
        run: |
          node main.js
        env:
          LEISHEN_USERNAME: ${{ secrets.LEISHEN_USERNAME }}
          LEISHEN_PASSWORD: ${{ secrets.LEISHEN_PASSWORD }}
